name: CI

on: push

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      #- name: HTML Style Checker
      #  uses: Cyb3r-Jak3/html5validator-action@master
      - name: Python Style Checker
        uses: cclauss/Find-Python-syntax-errors-action@master
      - name: Install requirements
        run: pip install -e '.[test]'
      - name: Run test
        run: coverage run -m pytest
      - name: Report
        run: coverage report
  docker_build_and_push:
    runs-on: [ubuntu-latest]
    needs: [run_tests]
    steps:
      - uses: actions/checkout@master
      - name: Login to docker.io
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t ${{ secrets.IMAGE }}:latest -f Dockerfile .
      - name: Push image to docker.io
        run: docker push ${{ secrets.IMAGE }}:latest 
  
